name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - website/**
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trust-check: false
          version: v0.2.7

      - name: Install packages
        run: wally install

      - name: Build plugin
        run: rojo build -o IPS2DevKit.rbxm

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: IPS2DevKit.rbxm
          draft: true